name: Testing Workflow Variables

on: 
  workflow_dispatch 

env:
   coud: google-cloud

jobs:
   greeting_job:
      runs-on: ubuntu:latest
      env: 
        Greeting: Hello
      steps: 
        - name: "Say Hello John it's Monday !"
          run: echo "$Greeting $First_Name is using $cloud!"
          env:
            First_Name: Pravin
